services:

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust  # Desativa a necessidade de senha
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony

  php:
    build:
      dockerfile: docker/php/Dockerfile  # Especifica o nome do Dockerfile
    image: php-custom:8.2
    container_name: php
    volumes:
      - ./symfony-app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - symfony
    working_dir: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"

  nodejs:
    build:
      dockerfile: docker/node/Dockerfile  # Especifica o nome do Dockerfile
    image: node-custom:lts
    container_name: nodejs
    working_dir: /usr/src/app
    volumes:
      - ./app/angular:/usr/src/app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - php
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - symfony

volumes:
  postgres_data:

networks:
  symfony:
    driver: bridge
